import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <SessionProviderWrapper>
            <Navbar />
            <main className="flex-grow pt-16 flex flex-col">{children}</main>
            <Footer />
          </SessionProviderWrapper>
        </div>
      </body>
    </html>
  );
}
