// src>app>layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "@/components/ConditionalNavbar";

import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <SessionProviderWrapper>
            <ConditionalNavbar />
            <main className="flex-grow pt-0 md:pt-16 flex flex-col ">
              {children}
            </main>
            <ConditionalNavbar mobile />
          </SessionProviderWrapper>
        </div>
      </body>
    </html>
  );
}
