// src>app>layout.js
import { Manrope } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "@/components/ConditionalNavbar";

import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body className="font-sans">
        <div className="flex flex-col min-h-screen">
          <SessionProviderWrapper>
            <ConditionalNavbar />
            <main className="flex-grow pt-0 md:pt-16 flex flex-col ">
              {children}
            </main>
            <ConditionalNavbar mobile />
          </SessionProviderWrapper>
        </div>
      </body>
    </html>
  );
}
